name: Spellcheck
on:
  pull_request:
  workflow_dispatch:
jobs:
  spell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v6
        with:
          files: "**/*.md"
          incremental_files_only: false
